version: "3.7"

services:

  backend:
    container_name: backend
    build: ./backend
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
      
  frontend_node1:
      container_name: frontend_node1
      build: ./frontend_node1

  frontend_node2:
    container_name: frontend_node2
    build: ./frontend_node2
    stdin_open: true
    ports: 
      - "2000:2000"
    volumes:
      - ./frontend_node2:/app  
    environment:
        - NODE_ENV=development
  
  nginx-orchestrator:
    container_name: nginx-orchestrator
    ports: 
      - 80:80
    depends_on: 
      - backend
      - frontend_node1
      - frontend_node2
    build: 
      context: .


  