version: "3.7"

services:

  backend:
    container_name: backend
    build: ./backend
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
      
  frontend_node1:
      container_name: frontend_node1
      build: 
        context: ./frontend_node1

  frontend_node2:
    container_name: frontend_node2
    build: 
      context: ./frontend_node2
      
  nginx-orchestrator:
    container_name: nginx-orchestrator
    ports: 
      - 80:80
    depends_on: 
      - backend
      - frontend_node1
      - frontend_node2
    build: 
      context: .


  